import Head from 'next/head'
import { useEffect, useState } from "react"
import { useRouter } from 'next/router'
import Appbar from "../components/appbar"
import Cards from "../components/card"

export default function Home() {
  const router = useRouter()
  const [Page, setpage] = useState({ loading: false, Message: "" })
  const [username, setUsername] = useState("")

  //user verification status using the token
  useEffect(() => {
    setpage({ ...Page, loading: true })
    fetch("api/token", {
      method: "POST",
      headers: {
        contentType: "application.json",
      }, body: JSON.stringify({ token: localStorage.getItem('token') })
    })
      .then(res => res.json())
      .then(res => {
        console.log(res)
        if (res.success) {
          setUsername(() => res.data[0].name)
          setpage({ ...Page, loading: false, Message: res.message })
        }
        else {
          router.push('/login')
        }
      })
  }
    , [])

  if (Page.loading) { return <h1>loading....</h1> }
  return (
    <div className='body'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Appbar name={username} />
      <Cards />
    </div>
  )
}
