import Head from 'next/head'
import { useEffect, useState } from "react"
import { useRouter } from 'next/router'
import Appbar from "../components/appbar"
import Cards from "../components/card"
import Grid from '@mui/material/Grid';

const images = [
  {
    link: "cow1.jpg"
  },
  {
    link: "cow2.jpg"
  },
  {
    link: "cow3.jpg"
  },
  {
    link: "cow4.jpg"
  },
  {
    link: "cow5.webp"
  },
  {
    link: "cow6.jpg"
  }
]


export default function Home() {
  const router = useRouter()
  const [Page, setpage] = useState({ loading: true, Message: "" })
  const [username, setUsername] = useState("")

  //user verification status using the token
  useEffect(() => {
    try {
      setpage({ ...Page, loading: true })
      fetch("api/token", {
        method: "POST",
        headers: {
          contentType: "application.json",
        }, body: JSON.stringify({ token: localStorage.getItem('token') })
      })
        .then(res => res.json())
        .then(res => {
          console.log(res)
          if (res.success) {
            setUsername(() => res.data[0].name)
            setpage({ ...Page, loading: false, Message: res.message })
          }
          else {
            router.push('/login')
          }
        })
    } catch (error) {
      setpage({ ...Page, loading: false, Message: error.message })
    }
  }
    , [])

  if (Page.loading) { return <h1>loading....</h1> }
  return (
    <div className='body'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Appbar name={username} />
      <Grid container spacing={2} justifyContent="center" className="listprodect">
        {images.map((a, i) =>
          <Grid key={i} item >
            <Cards {...a} />
          </Grid>
        )}
      </Grid>
    </div>
  )
}
